#import library to get data from the internet via APIs
import requests

import random
# import smtp library to send email through python code
import smtplib

import pandas as pd
import csv
# import time library to send email on specific time
import time
from email.message import EmailMessage

# API key to get data from website
API_KEY = "3b793ec3dc827224cf1478bb4ddbc8de"
# API website
API_END_POINT = "https://api.openweathermap.org/data/2.5/onecall"

# weather parameter to specify location of weather
weather_params = {
    "lat" :  46.4917,
    "lon" : 80.9930,
    "appid" : API_KEY,
    "exclude" : "minutely,daily,alerts"
}

# getting the response
response = requests.get(API_END_POINT, params = weather_params)
response.raise_for_status()
# convert response in json format
weather_data = response.json()

# get the weather data
curr_temp = round(weather_data['current']['temp']) - 273
feels_like = round(weather_data['current']['feels_like']) - 273
wind_speed = weather_data['current']['wind_speed']
desc = weather_data['current']['weather'][0]['description']
weather_slice = weather_data['hourly'][:12]

for hour_data in weather_slice:
    condition = hour_data['weather'][0]['id']
    if int(condition) < 600:
        will_rain = "It will rain today. Take an Umbrella with you."
        break
    else:
        will_rain = "It will not rain today. enjoy your day."


with open('User_email.csv', 'a+', newline="") as file:
    myFile = csv.writer(file)

# ask for user input
    num=int(input("How many user's to do you want to send mail notification? "))

    for i in range(num):
        k=input("User "+str(i+1)+": Please eneter the user's mail Id: \n")
        myFile.writerow([k])

    print(k)







#link for google form
link="https://forms.gle/NYNjXAEyF6sQLtzx6"

file = open("quotes.txt")
all_quotes = file.readlines()
quote = random.choice(all_quotes)
print(quote)


with open('User_email.csv') as file:
    reader = csv.reader(file)
    next(reader)
    for Email_Id in reader:

# while loop to send mail on specific time
        while True:
            data =  f" Welcome to Daily digest\n\n Motivational Quotes of the day\n {quote}\n Today's Weather information \n {will_rain}\n Today's Temperature : {curr_temp}°C \n Temperature Feels Like : {feels_like}°C \n Today's Wind Speed : {wind_speed} \n Over all Weather description : {desc}\n\n Click on below link to give your feedback \n {link}"
            msg = EmailMessage()
            my_email = "parthiv46patel@gmail.com"
            password = "P@telcanada"
            connection = smtplib.SMTP_SSL("smtp.gmail.com", 465)
            connection.login(my_email, password)
            msg['Subject'] = "Autogenerated notification"
            msg['From'] = my_email
            msg['To'] = Email_Id
            msg.set_content(data)

            connection.send_message(msg)
            connection.quit()
            time.sleep(60*1)
            print("Emial notification sent successfully !!!")
